apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  namespace: voting-app
  labels:
    app: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: dockersamples/examplevotingapp_worker
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets

